export const CITIES = [
  {
    City: "Тверь",
    mapLink: "https://dasha-gis32.github.io/Tver-/",
    id: 1,
    gitHubLink: "https://github.com/Dasha-gis32/Tver-",
  },
  {
    City: "Ярославль ",
    mapLink: "https://m-erts.github.io/map-okn-folium/",
    id: 2,
    gitHubLink: "https://github.com/m-erts/map-okn-folium",
  },
  {
    City: "Ростов Великий",
    Latitude: 57.195623,
    Longitude: 39.4131527,
    mapLink: "https://github.com/Basil-Dorin/mpa",
    gitHubLink: "https://github.com/Basil-Dorin/mpa",
    id: 3,
  },
  {
    City: "Тула",
    Latitude: 54.204836,
    Longitude: 37.6184915,
    mapLink: "https://trusoffcyrille.github.io/Folium-map-Tula-OKN-/",
    gitHubLink: "https://github.com/trusoffcyrille/Folium-map-Tula-OKN-/",
    id: 4,
  },
  {
    City: "Уфа",
    Latitude: 54.734791,
    Longitude: 55.9578555,
    mapLink: "https://printscreensys.github.io/interactive-web-map/",
    gitHubLink: "https://github.com/printscreensys/interactive-web-map",
    id: 5,
  },
  {
    City: "Челябинск",
    Latitude: 55.1644419,
    Longitude: 61.4368431,
    mapLink: "https://vslso.github.io/chelyabinsk_okn_map/",
    gitHubLink: "https://github.com/vslso/chelyabinsk_okn_map",
    id: 6,
  },
  {
    City: "Екатеринбург",
    Latitude: 56.8430993,
    Longitude: 60.6454086,
    mapLink: "https://nailbbot.github.io/Map-Ekb/",
    gitHubLink: "https://github.com/NAILbbot/Map-Ekb",
    id: 7,
  },
  {
    City: "Пермь",
    Latitude: 58.0091683,
    Longitude: 56.2269674,
    mapLink: "https://panssies.github.io/folium-map/",
    gitHubLink: "https://github.com/panssies/folium-map",
    id: 8,
  },
  {
    City: "Оренбург",
    Latitude: 51.768156,
    Longitude: 55.0969796,
    mapLink: "https://leone991.github.io/webmap/",
    gitHubLink: "https://github.com/leone991/webmap",
    id: 9,
  },
  {
    City: "Псков",
    Latitude: 57.8166994,
    Longitude: 28.3344734,
    mapLink: "https://eemeetu.github.io/Pskov",
    gitHubLink: "https://github.com/calmarina/3.2-MPA-Pskov",
    id: 10,
  },
  {
    City: "Петрозаводск",
    Latitude: 61.7781617,
    Longitude: 34.3640396,
    mapLink: "https://goorozia.github.io/mpa_3.2/",
    gitHubLink: "https://github.com/goorozia/mpa_3.2",
    id: 11,
  },
  {
    City: "Великий Новгород",
    Latitude: 58.5255698,
    Longitude: 31.2741928,
    mapLink:
      "https://nbviewer.org/github/a-berez/OKN_Novgorod/blob/main/index.html",
    gitHubLink: "https://github.com/a-berez/OKN_Novgorod",
    id: 12,
  },
  {
    City: "Дербент",
    Latitude: 42.0674251,
    Longitude: 48.2890907,
    mapLink: "https://lazarliang.github.io",
    gitHubLink: "https://github.com/lazarliang/lazarliang.github.io.git",
    id: 13,
  },
  {
    City: "Владикавказ",
    Latitude: 43.0252344,
    Longitude: 44.6659759,
    mapLink: "https://arthur-kislitsin.github.io/vladikavkaz-heritage-map/",
    gitHubLink: "https://github.com/arthur-kislitsin/vladikavkaz-heritage-map",
    id: 14,
  },
];
